name: Auto Deploy [main]

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy App Locally
        run: |
          cd /home/bin/clockbox
          git pull origin main
          source .venv/bin/activate
          pip install -r src/requirements.txt
          pkill gunicorn || true
          cd src
          nohup gunicorn -w 4 -b 0.0.0.0:8000 app:create_app > ../gunicorn.log 2>&1 &
