name: Auto Deploy [main]

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: [self-hosted, cloakbox]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/bin/clockbox
            git pull origin main
            source .venv/bin/activate
            pip install -r CloakBox_B/src/requirements.txt
            gunicorn -w 4 -b 0.0.0.0:8000 app:create_app
