name: Auto Deploy [main]

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy App Locally
        run: |
          cd /home/bin/cloakbox_api
          git pull origin main
          .venv/bin/pip install -r src/requirements.txt
          sudo -u cloakbox_deploy systemctl restart cloakbox